.PHONY: clean All

All:
	@echo "----------Building project:[ spf - Debug ]----------"
	@"$(MAKE)" -f  "spf.mk"
clean:
	@echo "----------Cleaning project:[ spf - Debug ]----------"
	@"$(MAKE)" -f  "spf.mk" clean
